# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [72]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

## Importing the dataset

In [73]:
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 2].values

## Splitting the dataset into the Training set and Test set

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15, random_state=0)

## Feature Scaling

In [83]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X_test)
sc.fit_transform(X_train)

array([[-0.58252386, -1.5099209 ],
       [ 2.09652308, -0.81097862],
       [-1.82636709,  0.17918961],
       [-0.19980287,  0.8490093 ],
       [-1.82636709, -1.27694014],
       [ 2.09652308,  0.38304778],
       [-1.34796585,  0.55778335],
       [-1.0609251 , -0.3450171 ],
       [ 0.18291812, -0.66536564],
       [ 0.37427862,  0.00445404],
       [-0.58252386,  2.33426165],
       [-0.29548312,  0.20831221],
       [-1.53932634, -0.19940412],
       [ 0.66131936, -1.39343052],
       [-1.0609251 ,  0.55778335],
       [-1.92204733,  0.35392518],
       [ 0.37427862,  0.2665574 ],
       [ 0.18291812, -0.28677191],
       [ 1.42676134, -1.04395938],
       [ 0.85267986,  1.08199006],
       [ 1.90516258,  2.15952608],
       [ 2.00084283,  0.38304778],
       [-1.34796585, -0.43238488],
       [-1.15660535, -1.01483678],
       [ 1.90516258, -0.927469  ],
       [ 0.37427862,  0.29567999],
       [ 0.18291812,  0.15006702],
       [ 2.00084283,  1.75180975],
       [ 0.75699961,

## Training the K-NN model on the Training set

In [84]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,p=2,metric='minkowski')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

KNeighborsClassifier()

## Predicting a new result

In [85]:
print(classifier.predict(sc.transform([[30,89000]])))

[0]


## Predicting the Test set results

In [86]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


## Making the Confusion Matrix

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[41  4]
 [ 5 10]]


0.85

## Visualising the Training set results

## Visualising the Test set results